#!/bin/bash

###############################################################################
# SmartTutor API Test Script
# Tests the deployed backend API endpoints
###############################################################################

set -e

echo "╔══════════════════════════════════════════════════════════════════╗"
echo "║                                                                  ║"
echo "║              SmartTutor API Test Suite                           ║"
echo "║                                                                  ║"
echo "╚══════════════════════════════════════════════════════════════════╝"
echo ""

# Load deployment info
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEPLOYMENT_INFO="${SCRIPT_DIR}/deployment-info.json"

if [ ! -f "$DEPLOYMENT_INFO" ]; then
    echo "❌ Deployment info not found. Please run deploy_backend.sh first."
    exit 1
fi

# Extract API endpoint
API_ENDPOINT=$(cat "$DEPLOYMENT_INFO" | python3 -c "import sys, json; print(json.load(sys.stdin)['apiEndpoint'])")

if [ -z "$API_ENDPOINT" ]; then
    echo "❌ API endpoint not found in deployment info"
    exit 1
fi

echo "🔗 API Endpoint: $API_ENDPOINT"
echo ""

###############################################################################
# Test 1: Generate Lesson Plan
###############################################################################

echo "═══════════════════════════════════════════════════════════════════"
echo "TEST 1: Generate Lesson Plan (POST)"
echo "═══════════════════════════════════════════════════════════════════"
echo ""

# Prepare request data
REQUEST_DATA='{
  "teacherId": "teacher_001",
  "classId": "class_8A",
  "subject": "Biology",
  "weekStartDate": "'$(date -v+monday +%Y-%m-%d 2>/dev/null || date -d "next monday" +%Y-%m-%d)'",
  "studentData": {
    "totalStudents": 25,
    "weakTopics": ["Photosynthesis", "Cell Division"],
    "averagePerformance": 72.5,
    "difficultyDistribution": {
      "easy": 8,
      "medium": 12,
      "hard": 5
    }
  }
}'

echo "📤 Sending request..."
echo "$REQUEST_DATA" | jq '.' 2>/dev/null || echo "$REQUEST_DATA"
echo ""

# Make API call
RESPONSE=$(curl -s -X POST \
    "${API_ENDPOINT}/teacher/lesson-plan/generate" \
    -H "Content-Type: application/json" \
    -d "$REQUEST_DATA")

# Check if response contains success
if echo "$RESPONSE" | grep -q '"success":true' || echo "$RESPONSE" | grep -q '"success": true'; then
    echo "✅ TEST 1 PASSED: Lesson plan generated successfully"
    echo ""
    echo "📋 Response Summary:"
    echo "$RESPONSE" | python3 -c "
import sys, json
try:
    data = json.load(sys.stdin)
    if 'lessonPlan' in data:
        plan = data['lessonPlan']
        print(f\"  Subject: {plan.get('subject', 'N/A')}\")
        print(f\"  Week Start: {plan.get('weekStartDate', 'N/A')}\")
        print(f\"  Weekly Goals: {len(plan.get('weeklyGoals', []))}\")
        print(f\"  Daily Lessons: {len(plan.get('dailyLessons', []))}\")
        print(f\"  Generated By: {plan.get('generatedBy', 'N/A')}\")
    else:
        print(json.dumps(data, indent=2))
except:
    pass
"
else
    echo "❌ TEST 1 FAILED: Lesson plan generation failed"
    echo ""
    echo "Error response:"
    echo "$RESPONSE" | jq '.' 2>/dev/null || echo "$RESPONSE"
fi

echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo "Full API Response (First 500 chars):"
echo "═══════════════════════════════════════════════════════════════════"
echo "$RESPONSE" | head -c 500
echo ""
echo "..."
echo ""

###############################################################################
# Test Summary
###############################################################################

echo "╔══════════════════════════════════════════════════════════════════╗"
echo "║                                                                  ║"
echo "║                    API Test Complete                             ║"
echo "║                                                                  ║"
echo "╚══════════════════════════════════════════════════════════════════╝"
echo ""
echo "Next Steps:"
echo "  1. Open teacher dashboard: open ui-prototype/pages/teacher-dashboard.html"
echo "  2. Click '🔄 Regenerate Plan' to test from UI"
echo "  3. Check CloudWatch Logs for Lambda execution logs"
echo "  4. Verify S3 bucket for stored lesson plans"
echo ""
echo "CloudWatch Logs:"
echo "  https://console.aws.amazon.com/cloudwatch/home?region=$(cat "$DEPLOYMENT_INFO" | python3 -c "import sys, json; print(json.load(sys.stdin)['region'])")#logStream:group=/aws/lambda/SmartTutor-LessonPlanGenerator"
echo ""
echo "S3 Bucket:"
echo "  https://s3.console.aws.amazon.com/s3/buckets/$(cat "$DEPLOYMENT_INFO" | python3 -c "import sys, json; print(json.load(sys.stdin)['s3Bucket'])")?region=$(cat "$DEPLOYMENT_INFO" | python3 -c "import sys, json; print(json.load(sys.stdin)['region'])")"
echo ""
